[window]
opacity=0.95

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
# AppleFontSmoothing = true



#[font.offset]
#x = 1
#y = 10
#
#[font.glyph_offset]
#y = 5

[keyboard]
bindings = [
{ key = "y", mods = "control", action = "Copy" },
{ key = "v", mods = "control", action = "Paste" },
{ key = "Space", mods = "control", action = "ToggleViMode" },
]

[cursor]

[general]
import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ] 

[terminal]


shell = "/usr/bin/nu"

